### PR TITLE
Stop Cycle API

### PR DESCRIPTION
**Pull request by niboobin**
Implemented Stop Cycle API feat, where users can stop an ongoing cycle. The key changes here are a new `POST /{id}/stop` endpoint to the cycle api that triggers the stop action for an active cycle. I also updated the cycle model with a status field (`ACTIVE`, `STOPPED`, and `COMPLETED` to track the current state of the cycle. I also modified the cycleschema to include status.

In the service layer, i implemented `stop_cycle` in `CycleService` to update the cycle’s status to "STOPPED" and set the `end_date` to today’s date. In the repository layer, I added `stop_cycle` in CycleRepo to handle the database update for status and end_date.

Thank you, and if there are any suggestions for improvements please let me know.

### CODE REVIEW

**Review by fiardiel — CHANGES_REQUESTED** [review]
Hi, Obin. I see that you have implemented the stop cycle method. I do think that your implementation is solid. Some improvements to be made maybe test the ENUM on the models including the stop method in a separate test file (such as a test for the model).

However, there's one issue, you deleted an important file namely `.coveragerc`, it shouldn't be deleted, you need to re-add that back before merging

**Comment by niboobin** [comment]
my fault, i dont know how it got deleted but i already added it back.

**Review by fiardiel — APPROVED** [review]
Okay obin nice

**Review by rauloaul — APPROVED** [review]
hehe, nice obin!~

**Pull request merged**
