### PR TITLE
Task 153 set status

### PR DESCRIPTION
**Pull request by rauloaul**
## Implement `set_status` feature

Hello, I've already do `set_status` implementation on `Tasks` Backend.

## Description:

- Added the set_status API to update the status of a task based on its ID.
- Implemented validation for the status field using TaskStatusSchema.
- Added error handling to return a 404 Not Found if the task ID does not exist.
- I also Implement SOLID on this feature
- All the tests applies 100% Code Coverage

Screenshot 2024-11-21 at 22 59 02

If you guys want to add something please let me know

### CODE REVIEW

**Review by fiardiel — APPROVED** [review]
Good job, Rafif!

**Review by niboobin — APPROVED** [review]
nice work rafif

**Comment by rauloaul** [comment]
Hello guys, I did some refactoring again on this branch, because after I check, the status field updated into `TaskStatus.DONE` or `TaskStatus.TODO` due to wrong implementation on using enums

**Review by niboobin — APPROVED** [review]
good work on the feature

**Pull request merged**
