### PR TITLE
Pbi 47 crud pond

### PR DESCRIPTION
**Pull request by rauloaul**
This are the changes that I've made for `CRUD Pond Backend`:

- Changing the Authentication using the `ninja_jwt` Authentication for the Pond API
- Changing the Pond models `volume` into : 
    - `length`
    - 'width`
    - `depth`
- Changing the API to implement the models changes
- Also adding test for models

### CODE REVIEW

**Review by fiardiel — APPROVED** [review]
Oh, there is a change in the model? Fine then, I will update the frontend right away!

**Review by niboobin — APPROVED** [review]
Good work, next im updating the frontend based on your changes

**Review by fiardiel — APPROVED** [review]
nice

**Comment by raisaafadilla** [comment]
nice

**Review by raisaafadilla — APPROVED** [review]
nice!

**Pull request merged**
