### PR TITLE
CRUD Pond Quality

### PR DESCRIPTION
**Pull request by fiardiel**
A recap of what I did in this pull request (NOTE: Commits start from Oct 1, 2024)
- Created an app for pond quality
- Created model for pond quality
- Created a schema for pond quality input and output
- Created API for CRUD pond quality
- Covered 100% of the code for API and model for CRUD Pond Quality

These are the files that needs reviewing: `pond_quality/api.py`, `pond_quality/models.py`, `pond_quality/schemas.py`

Thank you, please give some feedback on the API

### CODE REVIEW

**Review by niboobin — APPROVED** [review]
The api is already well structured, i can see that youre already using JWT auth.
For models, youre using `MaxValueValidator` and `MinValueValidator` for the `ph_level`.
Maybe add other validators for other fields also. And maybe You can set the `image` so that it only accepts `jpg` or `png`.

**Comment by fiardiel** [comment]
> The api is already well structured, i can see that youre already using JWT auth. For models, youre using `MaxValueValidator` and `MinValueValidator` for the `ph_level`. Maybe add other validators for other fields also. And maybe You can set the `image` so that it only accepts `jpg` or `png`.

Thanks for the feedback. The reason I didn’t input a validator for other than ph_level was that I wasn’t certain about their maximum and minimum value. Anyway, I will add the validator on. Also for the image do we really need to make it only accept jpg or png?. Thanks in advance

**Comment by niboobin** [comment]
> > The api is already well structured, i can see that youre already using JWT auth. For models, youre using `MaxValueValidator` and `MinValueValidator` for the `ph_level`. Maybe add other validators for other fields also. And maybe You can set the `image` so that it only accepts `jpg` or `png`.
> 
> Thanks for the feedback. The reason I didn’t input a validator for other than ph_level was that I wasn’t certain about their maximum and minimum value. Anyway, I will add the validator on. Also for the image do we really need to make it only accept jpg or png?. Thanks in advance

That is just my opinion though, but its not that necessary now that i think about it, it can avoid potential file handling issues down the line, would love to hear what the others think.

**Comment by fiardiel** [comment]
> That is just my opinion though, but its not that necessary now that i think about it, it can avoid potential file handling issues down the line, would love to hear what the others think.
Okay then, for now I'll try to add the validator to the model by clarifying the requirements from the stakeholders

**Review by rauloaul — APPROVED** [review]
Great work rafi

**Review by raisaafadilla — APPROVED** [review]
Great job Rafi! Everything looks well-structured

**Pull request merged**
