### PR TITLE
Pbi 47 crud pond

### PR DESCRIPTION
**Pull request by rauloaul**
- Create Pond Models
- Implement all test on each feature
- Implement CRUD for Pond
- Enabling users authorization on each feature

I already fixing few errors based on last pull request that I closed, maybe you guys have any suggestions?

### CODE REVIEW

**Comment by niboobin** [comment]
It is good enough, good job rafif

**Comment by fiardiel** [comment]
Great job, pip! I cannot wait to use the API that you made for the frontend app

**Comment by fiardiel** [comment]
Great job, pip! I cannot wait to use the API that you made for the frontend app

**Review by fiardiel — APPROVED** [review]
I think that it's good enough

**Review by niboobin — APPROVED** [review]
Very good rafif, i approve

**Comment by rauloaul** [comment]
Okay I will merge it to staging branch

**Pull request merged**
