### PR TITLE
Task 116 r food sampling

### PR DESCRIPTION
**Pull request by raisaafadilla**
I implemented code to retrieve and read the food sampling features, allowing users to view the food amount and the creation date. I also added a foreign key for the cycle in the models. Please feel free to provide any feedback. Thank you!

### CODE REVIEW

**Review by niboobin — APPROVED** [review]
Great work on implementing the backend part of read food sampling, now i can change the mocked version in the frontend into a proper server action where can fetch your api to display the food sampling.

**Review by rauloaul — APPROVED** [review]

**Comment by niboobin** [comment]
bang konflik bang

**Review by fiardiel — CHANGES_REQUESTED** [review]
I'm sorry, I just found out now. There were no get latest quality function. I think that we need that function on the frontend. You can either sort your list food sampling by recorded date, or create another api for get the latest sampling. I think it's better to do both

**Comment by fiardiel** [comment]
I also think that you need to incorporate Kevin's changes into your code so that the merge conflicts go away

**Comment by fiardiel** [comment]
> I'm sorry, I just found out now. There were no get latest quality function. I think that we need that function on the frontend. You can either sort your list food sampling by recorded date, or create another api for get the latest sampling. I think it's better to do both

Sorry, I think you only need to make a get latest quality function, the others aforementioned are not necessary

**Pull request merged**
